name = "forward-dated-emails"
main = "src/index.js"
compatibility_date = "2024-12-19"
account_id = "0a15c5f9d39350baa992ff9f48efc1c8"

# Email routing configuration
[email]
# This worker handles email events
