# public config; deploy with `wrangler deploy`
name = "forward-dated-emails"
main = "src/index.js"
compatibility_date = "2024-12-19"
account_id = ""


[email]
# this worker handles email events

[vars]
UTC_OFFSET = -4
# UTC offset for timezone (valid range: -12 to +14)
# examples: -4 for ET, -7 for PT, 0 for GMT, +8 for SGT

FORWARD_TO = ""
# email address to forward messages to